### ISSUE TITLE
[FEATURE REQUEST] Add ability to fire notices only for specific subnets

### ISSUE THREAD

**Issue by dwdixon** [corelight/zeek-long-connections#2]
In order to weed out the noise of enabling notices for all long connections and focus in on the high priority/sensitivity networks where long connections may be a big red flag, having the ability to only enable notices for specific subnets would be an amazing feature to add to this already great bro package.  Thank you!

**Comment by dwdixon** [comment]
@sethhall I just happened to come across this again, thinking that this may already be possible and I just hadn't had the time to look into it more at the time I posted this?  This might not even make sense but I'll have to dig back into it at some point...just wanted to note that here.

**Comment by sethhall** [comment]
I've wavered on configuration options like this forever because it's something that we would have traditionally handled through the notification framework, but I can see the semantics of handling it directly in the package are appealing.  I think I'll go ahead and add an option.
